# Generated by Django 6.0.6 on 2026-06-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_exercise_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
